# BlueMap-Factions configuration
# https://github.com/hucario/BlueMap-Factions#config

# Seconds between checks for marker updates
update-interval: 30

# Max members listed in %members%, %member_display_names%, and %member_uuids%
max-listed-members: 3

# Divider between eachMemberHTML in %membersHTML%
members-split: ''


dynamic-faction-colors: true


style:
  # default border settings
  border-color: '#FF0000'
  border-opacity: 0.8
  border-width: 3
  # default fill setting
  fill-color: '#FF0000'
  fill-opacity: 0.35
  # How high should the marker be?
  min-y-height: -64
  max-y-height: 150
  # Is the marker obstructed by things in its way?
  depth-test: true
  home-icon-enabled: false
  # Path to icon on web or a link
  home-icon: assets/house.png

translation:
  and-x-more: '<div class="xMoreMembers">+%1 more</div>'

bannerHTML: '<img class="popupBanner" src="%banner_url%">'
iconHTML: '<img class="popupIcon" src="%icon_url%">'
# This is a multiline string!
# See the rules for editing this at https://yaml-multiline.info/
discordHTML: |-
  <a class="discordLink" href="%discord_link%">
    <img class="discordImg" src="assets/img/discordIcon.svg">
    <span>Faction Discord</span>
  </a>
  
  
# This is hooked into PlaceholderAPI.
# This is a multiline string!
# See the rules for editing this at https://yaml-multiline.info/
eachMemberHTML: |-
  <div class="member %is_leader%">
    <img src="https://minotar.net/avatar/%player_uuid%/100.png" class="memberFace">
    <span class="displayName">%essentials_nickname_stripped%</span>
    <span class="userName">%player_name%</span>
  </div>
  
  


# HTML for faction popup, placeholders documented in README
# This is a multiline string!
# See the rules for editing this at https://yaml-multiline.info/
popup: |-
  <div class="nationPopup">
    %bannerHTML%
    <div class="iconGroup">
      %iconHTML%
      <div class="rightGroup">
        <span class="title">%name%</span>
        <p class="description">“%description%”</p>
      </div>
    </div>
    <label class="membersLabel">Members</label>
    <div class="members">
      %membersHTML%
    </div>
    <div class="buttonsRow">
      %discordHTML%
      <div class="balance">
        <span class="actualBalance">$%balance%</span>
      </div>
    </div>
  </div>
  
  