name: BlueMap-Factions
description: 'BlueMap addon for showing Factions on your map'
version: '${version}'
author: 'Hucario <gritty.pen4969@hucar.io>, Antti <antti@antti.codes>'
main: io.hucar.bluemapfactions.BlueMapFactions
api-version: 1.16
folia-supported: true
depend: [ BlueMap, Factions, PlaceholderAPI ]